version: "3.8"

services:
  db:
    image: mariadb:11.1.2
    ports:
      - 3310:3306
    environment:
      MARIADB_DATABASE: proyectoCopal
      MARIADB_ROOT_PASSWORD: 1234_()5678
      MARIADB_USER: bender
      MARIADB_PASSWORD: laniakeaSuperCluster
    healthcheck:
        test: "/usr/bin/mariadb --user=bender --password=laniakeaSuperCluster --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10

  front:
    build: .
    ports:
      - 4200:80

  back:
    build:
      context: ../t2-s3-socios-back
    ports:
      - 8080:80
    environment:
      - FRONTEND_URL=http://localhost:4200
      - DB_URL=jdbc:mariadb://db:3306/proyectoCopal?allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=bender
      - DB_PASSWORD=laniakeaSuperCluster
      - SPRINGBOOT_HIBERNATE_DDL_AUTO=create
      - SPRINGBOOT_PORT=80
    depends_on:
      db:
        condition: service_healthy
